#!/bin/sh

set -eu

# set console style constants
info=$(setterm --foreground cyan --bold on)
crit=$(setterm --foreground white --background red --bold on)
reset=$(setterm --default)

# APT
echo "${info}######################################## APT${reset}"
sudo apt update
sudo apt full-upgrade

# snap
if command -v "snap" >/dev/null; then
  echo "${info}######################################## Snap${reset}"
  sudo snap refresh
fi

# reboot
if [ -f /var/run/reboot-required ]; then
  echo "${crit}"
  echo "########################################"
  echo "      A reboot is recommended now!      "
  echo "########################################"
  echo "${reset}"
fi
